name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # runs-on: ubuntu-latest # node 11 fails with Python 2 exception for print
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: npm run docker-build
      - run: npm run docker-start

  verify-json-validation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file-name: [charactermap, tokenmap]

    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON ${{ matrix.file-name }}.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /tests/schemas/${{ matrix.file-name }}_schema.json
          INPUT_JSONS: /server/json/${{ matrix.file-name }}.json
